swagger: "2.0"
info:
  description: "Cloud Endpoints DNS"
  title: "Cloud Endpoints DNS"
  version: "1.0.0"
paths: {}
host: "store.endpoints.tenant-management-394215.cloud.goog"
x-google-endpoints:
- name: "store.endpoints.tenant-management-394215.cloud.goog"
  target: "34.111.130.170"
