kind: NamespaceSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: whereami-fleet-scope-selector
spec:
  mode: dynamic
  selector:
    matchLabels: 
      fleet.gke.io/fleet-scope: team-whereami